version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=production
    restart: always